language: python
sudo: false
python:
    - 3.5
    - 3.8

matrix:
  allow_failures:
    - python: 3.8

services:
    - xvfb
install:
    - "sh install_test_deps.sh"
    # Remove the next two lines after our test suite is compatible with selenium 3.
    - "pip uninstall -y selenium"
    - "pip install selenium==2.53.6"
    - "pip uninstall -y xblock-drag-and-drop-v2"
    - "python setup.py sdist"
    - "pip install dist/xblock-drag-and-drop-v2-*.tar.gz"
    - "pip install pylint"
script:
    - pycodestyle drag_and_drop_v2 tests --max-line-length=120
    - pylint drag_and_drop_v2
    - pylint tests --rcfile=tests/pylintrc
    - python run_tests.py
notifications:
    email: false
addons:
    firefox: "43.0"
